### ISSUE TITLE
Find cause of randomly failing tests in travis by increase logging of the tmux environment

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#123]
With the increased logging, test have failed with:
```
Exception during setUp: callProcess: tmux "new-session" "-x" "80" "-y" "24" "-d" "-s" "purebredtest" "-n" "purebred" (exit 1): failed

failed to connect to server

failed to connect to server
```
It would now be interesting as to why the server is gone. Increasing the logging of the tmux session by invoking `tmux` with multiple `-vvv` might give a clue.

Alternatively perhaps, we should look at *not* starting/killing each session for each test run, but instead generate a random session name. Although that might not scale very well ...

**Comment by romanofski** [comment]
I've tried increasing the logging output, but it's unfortunately not much help to pin point the problem. I'll try reproducing it on a ubuntu trusty platform ...

**Comment by frasertweedale** [comment]
I'm thinking about this one.
It it (usually?) `new-session` that is failing, with "failed to contact server".  I think I also recall seeing "duplicate session" sometimes?  So I reckon this happens because:

1. after previous process exits, tmux server is still tearing down the session.  Meanwhile, the `tmux` process running the next `new-session` command observes that there is a server (presumably by looking for a particular unix domain socket).  But just then the server finally destroys itself and goes away.  This is the "failed to contact server" problem.

2. For the duplication session case, it is the same root cause, but the tmux server hasn't even destroyed the old session yet, by the time the next `new-session` command arrives.  This is the "duplicate session" problem.

Each part requires its own solution:

1. A single "keepalive" session that exists for the duration of the tests would prevent the "failed to contact server" error.
2. Random (or sequential) names will prevent the "duplicate session" error.

This is all just a theory of course.  But they seem like reasonable things to try.

**Comment by frasertweedale** [comment]
For keeping server alive, see also `tmux start-server` and `kill-server` commands and `exit-unattached off` server option.

**Comment by romanofski** [comment]
I've always skipped an explicit `tmux start-server` since the documentation mentions
>> If no server is started, attach-session will attempt to start it; this will fail unless sessions are created in the configuration file.

Increasing the logging output has actually not resulted in anything valuable (see [Job 301](https://travis-ci.org/purebred-mua/purebred/jobs/319614990)).

I actually haven't seen any duplicate session errors unless I manipulated the tear down function which failed to remove the old session.

I thought I had observed the tmux server crashing/exiting  in a container based on a `ubuntu:trusty` image.  After issuing a kill-session command, the server exited or crashed (not sure what). Yet, I can't reproduce this problem any more. So far I didn't browse the issues if it was maybe a problem in an older version of tmux.

So not really sharing your hypothesis there, unless I totally missed those duplicate session errors.

**Comment by frasertweedale** [comment]
Actually now I recall that I have seen it during debugging, where I add a long sleep to the test suite,
then manually connect to the session to poke around.  Then I forget to kill the session before
running the tests again, and end up with duplicate session :)

Anyhow I think it would be good hygiene to use a different session name for each test.
And we know we want to try out the "keepalive" session to see if it avoids the "failed to contact server" issue.  I'll push a PR tonight and we can hammer Travis, say... 10 times, to see if it avoids the issue.

**Comment by romanofski** [comment]
Yeah agree having a new, random session name would be good. Perhaps it would be helpful if we could prefix the random value with the testcase name or testcase group or both. That would help during debugging sessions.

I'm also wondering if there is an upper limit as to how much sessions you can create or if it's simply bound by your operating systems resources. Anyhow, interesting to see how this goes.
