### ISSUE TITLE
text search of mail body

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#279]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to be able to search for strings within a mail body.

**Describe the solution you'd like**
A simple search feature (case insensitive string match is fine; regex is overkill), which highlights matches.

**Describe alternatives you've considered**
Pipe to less?  Yuck.

**Additional context**
.

**Comment by romanofski** [comment]
Hahaha .. pipe to less. But you're right... that could be a workaround. 

This is certainly needed...

**Comment by romanofski** [comment]
I had a bit of a look through Brick and at the moment it looks we might need to implement something ourself. Perhaps we'll need to implement something like `txtWrap` which creates a `Widget n` using [Data.Text.Markup](https://hackage.haskell.org/package/brick-0.47.1/docs/Data-Text-Markup.html). Using markup lacks the ability to wrap long text, while `txtWrap` lacks the ability to markup.

I'm not sure how well this will play with the scroll state, but I guess we'll see. I've also found this discussion https://github.com/jtdaugherty/brick/issues/232 which seems related.
If the function turns out generic enough, it's perhaps something we could contribute to Brick.

**Comment by romanofski** [comment]
With haskeline integration currently pending I think I'll have a look into this.
I presume from a users point of view we want something along:

1. Press `/` to get an editor
2. Type in the word
3. If the word is in the body, move the viewpoint closes to the word
4. Highlight all occurrences
5. Press `n` to jump to next occurrences and wrap the search again back to the first occurrence
6. If the word isn't found, show a little notification (currently probably looking like an error).

**Comment by romanofski** [comment]
Looking at our current implementation, I've realised that there are two bits to this implementation:
1. Taking input, finding the words and scrolling to the first occurrence using [scroll requests]( https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#scrolling-viewports-with-visibility-requests)
2. Add the markup to the text which highlights the occurrences

**Comment by frasertweedale** [comment]
Yes, agree, and (2) is the prerequisite of (1)... or at least a prerequisite of (1) being able to affect anything.

**Comment by romanofski** [comment]
As it turns out, the first point is easy, but actually needs the second point to be implemented first. Reason being is that any text wrapping can only be done when we know the terminal or rendering width which is not available until we have access to the rendering context.

Thus the index can only build after/during the widget is rendered. I'm not so sure how this can be done honestly, since I don't think we have access to the `AppState` during construction of the widget.

However we need a good representation of the body and the entities in general, which we decided to represent in an AST. I'll embark on the AST first and then come back to the index.

**Comment by romanofski** [comment]
Just to note down another thought. In case there is no way to update or generate the index which is used to scroll, we could probably just approximate it. I'm almost certain we won't be able to access the terminal width outside of the rendering context of the widget. On the other hand we could produce the scroll indexes for a fixed width since being off by two or three lines won't be such a big problem. I suppose it only because tricky if the terminal really is too narrow or wide.

**Comment by romanofski** [comment]
I made some progress with this on the weekend. I've started off parsing the chosen entity into a structure representing token and white spaces. On top came the annotation whether we have a match for a given input string.

That resulted in the expected behaviour, but I felt rendering every word with brick markup annotation not to be a scalable approach.

I changed the implementation to be line based like this:

```Haskell
newtype Mailbody = Mailbody [Line]

type Match = (Int, Int)  -- offset, length of the highlight
data Line = Line [Match] T.Text
```
and during rendering, I basically set the matches using Bricks [markupSet](https://hackage.haskell.org/package/brick-0.50/docs/Data-Text-Markup.html#v:markupSet). I wrap the lines hard at the 72 mark at this point in time. This really needs to go into a new widget. The `Line` gives me the possibility to also calculate the line numbers as steps for scrolling.

The matches are produced using [breakAll](https://hackage.haskell.org/package/text-1.2.3.1/docs/Data-Text.html#v:breakOnAll) with it's abysmal performance, but hey... first iteration.

This gets me as far as highlighting and cycling through the current matches, including scrolling.

Current Caveats/Bugs/Thoughts:
* There is no absolute scrolling unfortunately. I currently simulate it by scrolling to the top and then scrolling the absolute amount to the line number. Unfortunately that doesn't scale well with terminal resizes.
* The line numbering is done when I iterate through all `Line`s in the mailbody using `ifoldr` and saved in a `FocusRing` with the matches. The match in the current line in the focus ring is compared during rendering. The highlighting has one draw back, which is, if there is more than one line with the same offset and length, we get two highlighted words.
* The function for searching `breakOnAll` is not case insensitive apart from it's bad performance. Perhaps Boyer Moore would fit here well too.
* The current `MailBody` data type would probably better be a `Paragraph` so we can show nesting with quoted mails.
* Can't decide yet if I want an additional semantic type for words and white spaces in the `Line`. I'll leave that out for now until it becomes apparent.
* The current AST only represents the preferred entity we pull out of the email. It currently doesn't represent additional leaf nodes indicating what other entities are in the mail.

**Comment by romanofski** [comment]
First pass on the widget and I realise that my current approach doesn't work as I imagined. I need to represent matches or highlights in the AST (e.g. in the `MailBody`) and not as positions.
At some point I need to render the entire AST and when I start to break the lines the match positions are obviously off. For example if the match on a long line was at 80, it will be on 10 after the line break in the second line.

Since I was wondering if I should go back to representing words and whitespaces. I guess I have the answer now.

**Comment by frasertweedale** [comment]
On Thu, Oct 10, 2019 at 12:13:20AM -0700, Roman Joost wrote:
> First pass on the widget and I realise that my current approach doesn't work as I imagined. I need to represent matches or highlights in the AST (e.g. in the `MailBody`) and not as positions.
> At some point I need to render the entire AST and when I start to break the lines the match positions are obviously off. For example if the match on a long line was at 80, it will be on 10 after the line break in the second line.
> 
> Since I was wondering if I should go back to representing words and whitespaces. I guess I have the answer now.
> 

We should see if there's any literature on data structures for
markup suitable for applications like DOM rendering or text editing
with syntax highlighting.

We are not the first people to face this problem.  Hopefully there
is literature that can help us.

**Comment by romanofski** [comment]
I agree and if you stumble over something I'd be interested in what you find.

I got an idea this morning. I think I've looked at this from the perspective. Instead of parsing the mail body into an AST and breaking the lines when rendering (since that's the only time we know of the available terminal width), perhaps we should do it the other way around: break the text at a fixed width, before parsing them into an AST. Then we have no problem knowing how many rows we need to scroll for a highlighted word.

The disadvantage is, that we don't have text automatically taking up the terminal width, but I would be willing to sacrifice it for now. The previous method (break long lines when rendering) had the disadvantage that we couldn't calculate how many rows we had to scroll and used an approximation by forcing line breaks.

None of this is perfect, but IMHO it's good enough for a 1.0 release.

**Comment by romanofski** [comment]
@frasertweedale  I've pushed my work in progress on  feature/279-text-search-of-mail-body if you want to give it a whirl.

**Comment by romanofski** [comment]
Hm thinking of calling it a break for now before falling into the rabbit hole. I have text search working and an additional patch which allows to automatically pipe and view the output (handy for text/html to be piped through elinks etc). All of it is searchable. I think the next step I was going for is to actually render all entities in a flat list if possible (mutt called it autoview).

Having said that, I think there is currently bigger fish to fry than going and implement full autoview support.

I think what I do to wrap this up now is to extend the data type we currently have as `MailcapHandler` to signal that the piped output can be read back in (the mailcap used `copiousoutput`) instead of using a separate list of `MailcapHandler`s (see https://github.com/purebred-mua/purebred/blob/feature/279-text-search-of-mail-body/src/Types.hs#L484).

Have both of those patches and call it quits for #279. That gives us search of text fragments for the preferred, rendered content type and additionally the ability to display output of entities piped through an external command.

@frasertweedale what do you think?

**Comment by frasertweedale** [comment]
@romanofski strong agree; `copiousoutput` is defined in https://tools.ietf.org/html/rfc1524.  We want our data type to move closer to that (so eventually we can parse a mailcap file into it), and implement all the semantics (or the sensible parts).  `copiousoutput` is one such sensible aspect :)
