### ISSUE TITLE
Conditional Actions

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#294]
**Is your feature request related to a problem? Please describe.**
I would like to chain actions which perform independent actions based on a condition. For example: `openAttachment :: Action 'ViewMail ctx (T.Next AppState)` is such an action. It depends if the configuration has a default command registered, otherwise focuses (read makes visible) the editor to type in a command.

Another example: `switchComposeEditor :: Action 'Threads 'ListOfThreads AppState` is an action which, depending if a composition is underway, goes back to the compose editor, otherwise does nothing. It could otherwise be asking for composing a new mail.

My point being is, that these actions are all or nothing actions which can't really be chained like most of others. I think it would be great if we could split these actions based on a condition.

**Describe the solution you'd like**
I haven't thought about this thoroughly and what implications it has. At this point, the actions don't have access to any form of context, so using Haskells `if then else` will probably not work when registering the `Action`.

**Describe alternatives you've considered**
 Maybe we need a `ConditionalAction` which can accept two individual actions? I don't know.

**Additional context**
See examples

**Comment by frasertweedale** [comment]
So, turns out you can kinda sorta get a Monad instance, if you generalise the Action type just a bit.  See https://github.com/purebred-mua/purebred/commit/871de4a13a34b8bf1dea2e05f7bb394e745dde54.  That commit does not include a Monad instance, but the instance is straightforward (although it would violate the `(<*>) = ap` law).  This would give choice over "next action" based on result of current action.

It was nice to see the Profunctor and Category instances shake out of such a small change in the type.

All that said, I am not sure it is the right approach.  First, I am not comfortable with the lawless Monad instance.  Second, I am simultaneously investigating a different change to the Action type, to use `StateT AppState (EventM Name) a` instead of `AppState -> EventM Name a`.  This change will allow some nice cleanups and easier way to set/read state from within actions.  The type will still admit Functor and Applicative instances, I think, as well as Monad with the same caveat as above.  This change is a large refactor so I'll just chip away at it and then we can see if we like the result or not.

**Comment by frasertweedale** [comment]
Can we close this now that actions use `MonadState AppState m`?

**Comment by romanofski** [comment]
Yeah lets close it.
