### ISSUE TITLE
`confEditor` config is unused

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#50]
We are not using this config.  When we invoke the editor to inspect `EDITOR` env var,
and default to `vi` explicitly at that point.

This may be another case of "default config is an `IO a`"...

The default action SHOULD use whatever is in `EDITOR` if set, otherwise use vi.

Thinking more about this it is a nice idea to have `IO FilePath` for this config too.
Use case: a user wants a single purebred config to work on different hosts, and the
config uses aspects of the environment to work out what to invoke.  For example if
we end up supporting Windows, the action could inspect the platform / environment / 
see what's installed and select the editor accordingly.

**Comment by romanofski** [comment]
Hah yes, we totally ignore that. 

I'm not really sure I understand why we need an `IO FilePath` for this, since it seems to me that it is something easily configurable without any IO interaction.

Even then, using just `IO FilePath` might actually not be enough tho. Since it's not only the editor you want, you might also want to pass arguments to the editor. E.g.

  vim -c 'set tw=72' -f +8

At the moment purebred just takes what's in the EDITOR variable and executes it in a shell which includes any arguments EDITOR is configured with.

**Comment by frasertweedale** [comment]
On Thu, Aug 31, 2017 at 12:49:16AM +0000, Roman Joost wrote:
> Hah yes, we totally ignore that. 
> 
> I'm not really sure I understand why we need an `IO FilePath` for
> this, since it seems to me that it is something easily
> configurable without any IO interaction.
> 
Don't you want the default behaviour to inspect `EDITOR` envvar?
Reading the environment is an IO computation:

    lookupEnv :: String -> IO (Maybe String)

> Even then, using just `IO FilePath` might actually not be enough
> tho. Since it's not only the editor you want, you might also want
> to pass arguments to the editor. E.g.
> 
>   vim -c 'set tw=72' -f +8
> 
Sure, then instead of `IO FilePath` we make it an `IO (FilePath,
[String])`, or something like that.

**Comment by romanofski** [comment]
Ah I understand now. Instead of performing the environment variable lookup somewhere in the code (deep down in UI.GatherHeaders.Main), rather make it the default in the config and let the user overwrite it with his config, right?

Then maybe leave it as `IO String` ? It seems for this kind of thing, using a shell is fine (don't need that much control over the editor process).

**Comment by romanofski** [comment]
This is merged.
