### ISSUE TITLE
Search which yields a large results takes too long

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#51]
A search which yields a large result takes quite a long time. I've profiled a bit and here are the stats:

Mail indexed in notmuch: 170297
notmuch search: *

* neomutt: 18s
* purebred: 32s
* alot: 1s (not even)

[purebred.txt](https://github.com/purebred-mua/purebred/files/1265415/purebred.txt)

**Comment by frasertweedale** [comment]
@romanofski awesome, thanks for the cost centres.

Do the programs definitely do the same thing?  For example, you are
not just loading every message but reading the tags of every
message.

Here's a few quick takeaways:

- detachPtr is surprisingly expensive (> 10%) but it can't be
  improved.

- message_get_filename is individually responsible for ~65% of the
  allocation of the entire program.  This is due to reading the
  filename into a `String` i.e. a cons list of `Char` (and the
  filenames tend to be longish).

  Recommendation: defer reading the filename until we actually need
  it.  Alternatively: change messageFilename to return a ByteString
  instead (still allocs, but should be way cheaper).

- Copying tags is an interesting case - we will be copying the same
  string over and over again.  Interning them could save a lot of
  copies (maybe notmuch itself interns them, though if it does we
  probably can't rely on this).  In any case, the main overhead here
  currently seems to be time spent iterating the notmuch_tags_t
  (~28% of program runtime), not alloc (~7%).

  Of that 28%, ~9% is notmuch_tags_valid and comparing the result to
  see if there are more items, ~5% is (notmuch_tags_get + copying
  the tag value + cons cell alloc), ~5% is notmuch_tags_move_to_next
  (advancing the iterator).  So ~15%..20% of the 28% is absolutely
  irreducible.  Similar ratios will apply for other iterators
  (messages, threads, etc) but there is a smaller number of those so
  it has a smaller impact overall.

- messageHeader is kind of expensive (~14% of runtime).  I suspect
  this is due to reading one of the headers that is not indexed
  ("To:").  If you avoid reading the To: header, how much does the
  runtime improve?

- You are reading the tags twice!  That's 28% of the execution time
  EACH.  The offending code is in `messageToMail` - you call
  tagsToText, then also call `isNewMail` which also gets the tags.
  Get the tag list ONCE and use it twice :)  Poof!  28% of the
  program runtime will vanish :)

**Comment by romanofski** [comment]
Ah cheers for the analaysis. A quick hack addressing the tag reading and throwing out the filename parsing reduces the load time to: (drumroll) 19s.

and I've got more profiling information for you if you're keen :)
[purebred.txt](https://github.com/purebred-mua/purebred/files/1265588/purebred.txt)

The filename parsing could really be delayed until the user views the mail. Fiddling with the header didn't have a big impact as you can imagine, but I guess it's something we could squeeze ... In a way it would be better to sort of stream the mails into the vector instead of loading them all. Not sure.

**Comment by frasertweedale** [comment]
Here's a ticket in *hs-notmuch* for improving performance of `messageHeader`:
https://github.com/purebred-mua/hs-notmuch/issues/12.  A similar thing can be done for tags
although it will only improve performance when writing tags, not reading.

**Comment by frasertweedale** [comment]
regarding "streaming the mails" we might be able to do it with `unsafeInterleaveIO`.  But I will leave that experiment for another day - for now it is actually useful to process everything fully - helps us to see where the bottlenecks are.

**Comment by romanofski** [comment]
Sounds good. I'll push my change to the double parsing of tags, but leave the rest for later to hack on. Actually thinking of it, perhaps better to make a separate item for it.

**Comment by romanofski** [comment]
I think we can close this one, since we've got a bunch of items we can work on to improve and then do this again after a while ...

**Comment by frasertweedale** [comment]
Yep, all of the actionable stuff from this round of analysis has been put into other tickets.
Closing.
